#/IronFilter/det/setFilterCellSpacing 76.0 cm #76.0 cm
/IronFilter/det/setFilterCellSpacing 86.0 cm #86.0 cm
#/IronFilter/det/setPolyHeight 10.0 cm #Scandium 30 cm for Maganese 10 cm rod height if you need zero spacing
/IronFilter/det/setPolyHeight 28.0 cm #Scandium 30 cm for Maganese 10 cm rod height if you need zero spacing
/IronFilter/det/setMultiplierLeadHeightFront 25.0 cm
/IronFilter/det/setModeratorAluminumHeight 40 cm
/IronFilter/det/setModeratorTitaniumHeight 7.0 cm # 10cm for Mn 5cm for Sc to get the DT position add the number till here
#/IronFilter/det/setModeratorTitaniumHeight 10.0 cm # 10cm for Mn 5cm for Sc to get the DT position add the number till here
/IronFilter/det/setMultiplierLeadHeightRear 30.0 cm
/IronFilter/det/setMultiplierLeadRadius 30.0 cm
/IronFilter/det/setModeratorAluminumRadius 25.0 cm
/IronFilter/det/setModeratorTitaniumRadius 25.0 cm
/IronFilter/det/setTestX 0 m
/IronFilter/det/setTestY 0 m
/IronFilter/det/setTestZ 0 m


/run/initialize
/tracking/verbose 0
/control/getEnv SEED
/control/getEnv a
/control/getEnv b

/random/setSeeds {a} {b}

/process/list
/run/printProgress 100

/filename/setFilename DTFridgelab_0.root

/run/beamOn 15961 #geom66
